# Generated by Django 3.0.5 on 2020-05-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rupi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=0)),
                ('tz', models.CharField(max_length=100)),
                ('start_time', models.DateField(null=True)),
                ('end_time', models.DateField(null=True)),
                ('start_times', models.DateField(null=True)),
                ('end_times', models.DateField(null=True)),
            ],
        ),
    ]
